### ISSUE TITLE
Denoise.rar password

### ISSUE THREAD

**Issue by ionmihalache** [Quark-Coder/siril-guide#1]
Hello,
please, which is the password for the Denoise.rar file?
Regards

**Comment by Quark-Coder** [comment]
@ionmihalache 
Hello!
Sorry I didn't notice earlier, I rarely check github. I resolve all questions about this in discord **quark_coder** or telegram **https://t.me/perfluorobutane**

**Comment by Quark-Coder** [comment]
Guide now uses GraXpert as noise reduction program.
